# write github action that create a storybook and stories of the available components 
name: storybook
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: build angular and restore
        run: |
          yarn
          yarn build
      - name: search for angular components in repo
        run: |
          find ./src -name "*.component.ts"   | while read file; do echo $file >> components.txt; done;
      - run: npm install -g @angular/cli
      - name: install storybook
        run: |
          echo "installing storybook"
          npx storybook@latest init
         
     # Use the sgpt command to ask GPT to create stories for the components

#      - name: Storybooks GPT
#        run: |
#          sgpt "generate stories in storybook format to following components,  support Storybook Controls, write me the response as a list of executable bash commands that create a file for each component and write the stories to the flle system. dont add
#          custom messages. $( cat components.txt )" > $commands
      
#      - name: execute storybook commands
#        run: |
#          echo "executing storybook commands"
#          cat $commands | while read command; do echo "executing $command"; $command; done;
      - name: generate story for each component
        run: |
          echo "generating story for each component"
          cat components.txt | while read component; do echo "generating story for $component"; npx sb generate component $component; done;
      - name: create pr to storybook branch
        run: |
          echo "creating pr to storybook branch"
          git checkout -b storybook
          git add .
          git commit -m "create storybook"
          git push origin storybook -f
          gh pr create --title "update storybook" --body "update storybook" --base main --head storybook
        
      - name: build storybook
        run: |
          echo "building storybook"
          npx sb build
      - name: deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
        
        
  
